# Generated by Django 4.0.3 on 2022-03-17 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TenderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('notice_number', models.CharField(max_length=150, unique=True)),
                ('tender_name', models.CharField(max_length=150)),
                ('procedure_state', models.CharField(max_length=150)),
                ('contract_type', models.CharField(max_length=150)),
                ('procurement_type', models.CharField(max_length=150)),
                ('estimated_value', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'e-licitatie romanian tenders',
            },
        ),
    ]
